from ALP_rescale.general.setup import*

couplings = [   'CBB',
                'CWW',
                'CGG',
                'Cll',
                'Cqq'
            ]

experiments = { 'NA62':         'NA62',
                'CHARM':        'CHARM',
                'NuCal':        'NuCal',
                'SHiP':         'SHiP',
                'DarkQuest':    'DarkQuest',
                'DUNE':         'DUNE',
                'SHADOWS':      'SHADOWS',
                'KOTOpnn':      'KOTO',
                'KOTOexclPnn':  'KOTO',
                'KOTOdump':     'KOTO',
                'KOTO2pnn':     'KOTO2',
                'KOTO2dump':    'KOTO2',
                'E137':         'E137',
                'E141':         'E141',
                'KLEVER':       'KLEVER',
                'KLEVERext':    'KLEVER',}

channels_decay = ['2Gamma',
                  '2El',
                  '2Mu',
                  '3Pi0',
                  '3Pi',
                  '2PiGamma',
                  '2Pi0Eta',
                  '2PiEta',
                  '2Pi0EtaPrim',
                  '2PiEtaPrim',
                  '2KPi0',
                  '2Pi2Pi0',
                  '4Pi',
                  '2Omega',
                  '2Kstar',
                  '2Phi'
                    ]

channels_production = [ 'primakoff',
                        'photonfrommeson',
                        'mixingPi0',
                        'mixingEta',
                        'mixingEtaPrim',
                        'Bmeson',
                        # 'Dmeson',
                        # 'BmesonK',
                        # 'BmesonKstar',
                        # 'DmesonPi',
                        # 'recast',
                        ]
reference_couplings = {'primakoff':         1,
                       'photonfrommeson':   1,
                       'mixingPi0':         1,
                       'mixingEta':         1,
                       'mixingEtaPrim':     1,
                       'Bmeson':            1,
                      #  'Dmeson':            1,
                      #  'BmesonK':           1e-10,
                      #  'BmesonKstar':       1e-10,
#                     #    'DmesonPi':          1e-10,
                      #  'recast':            1,
                       }
scaling_exponent =    {'primakoff':         2,
                       'photonfrommeson':   2,
                       'mixingPi0':         2,
                       'mixingEta':         2,
                       'mixingEtaPrim':     2,
                       'Bmeson':            2,
                      #  'Dmeson':            2,
                      #  'BmesonK':           1,
                      #  'BmesonKstar':       1,
                     #   'DmesonPi':          1,
                      #  'recast':            2,
                       }

# reference_couplings = {'primakoff':      1e-4,
#                        'photonfrommeson':1e-4,
#                        'mixing':         1e-4,
                      #  'BmesonK':        1e-10,
                      #  'BmesonKstar':    1e-10,
#                        'Bmeson':         1,
#                        'Dmeson':         1e-10}